### PR TITLE
Framel 8.46.0

### PR DESCRIPTION
**Pull request by rhyspoulton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rhyspoulton** [comment]
@duncanmmacleod I have decided to remove the translation of the cmt version tag and instead use the standard version tag, which we need the developer to create. This is also because the translation would not translate the `v8r60` tag correctly as it would translate it to `8.46`, so missing the minor version number.

**Comment by duncanmmacleod** [comment]
@rhyspoulton, this build is failing because the new `ctypesgen` stuff doesn't build properly when `ENABLE_C=false` is given to the build, so the C library isn't built at the same time.

**Comment by duncanmmacleod** [comment]
@rhyspoulton, f786f7b configures the build to skip `python-framel` on Windows, as we discussed.

**Comment by rhyspoulton** [comment]
Thanks for working on the @duncanmmacleod, please approve when you are happy for this to be merged.

**Review by duncanmmacleod — APPROVED** [review]

**Pull request merged**
